# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
